2020-06-19 14:00:36,888:DEBUG:certbot.main:certbot version: 0.30.2
2020-06-19 14:00:36,889:DEBUG:certbot.main:Arguments: ['--non-interactive', '--config', '/etc/letsencrypt.ini', '--cert-name', 'npm-2', '--agree-tos', '--email', 'tmvp91@gmail.com', '--preferred-challenges', 'dns,http', '--webroot', '--domains', 'vscode.dathaddenwetochafgesproken.nl']
2020-06-19 14:00:36,890:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-06-19 14:00:36,904:DEBUG:certbot.log:Root logging level set at 20
2020-06-19 14:00:36,905:INFO:certbot.log:Saving debug log to /config/log/letsencrypt/letsencrypt.log
2020-06-19 14:00:36,906:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2020-06-19 14:00:36,910:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7fc967979a58>
Prep: True
2020-06-19 14:00:36,911:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7fc967979a58> and installer None
2020-06-19 14:00:36,911:INFO:certbot.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2020-06-19 14:00:36,915:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/89244674', new_authzr_uri=None, terms_of_service=None), f17fa8d41b184b1321332c2c31c39b9e, Meta(creation_dt=datetime.datetime(2020, 6, 19, 13, 55, 24, tzinfo=<UTC>), creation_host='6102584403b0'))>
2020-06-19 14:00:36,916:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-06-19 14:00:36,918:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
2020-06-19 14:00:37,426:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-06-19 14:00:37,427:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 19 Jun 2020 14:00:37 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "7sJE_n6xi78": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-06-19 14:00:37,427:INFO:certbot.main:Obtaining a new certificate
2020-06-19 14:00:37,617:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0001_key-certbot.pem
2020-06-19 14:00:37,618:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0001_csr-certbot.pem
2020-06-19 14:00:37,619:DEBUG:acme.client:Requesting fresh nonce
2020-06-19 14:00:37,619:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-06-19 14:00:37,746:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-06-19 14:00:37,747:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 19 Jun 2020 14:00:37 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 01018QeHuytsbC0V9tTq3YW7ThirrRVvxewkE3HtsItwORM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-06-19 14:00:37,747:DEBUG:acme.client:Storing nonce: 01018QeHuytsbC0V9tTq3YW7ThirrRVvxewkE3HtsItwORM
2020-06-19 14:00:37,747:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "vscode.dathaddenwetochafgesproken.nl"\n    }\n  ]\n}'
2020-06-19 14:00:37,750:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvODkyNDQ2NzQiLCAibm9uY2UiOiAiMDEwMThRZUh1eXRzYkMwVjl0VHEzWVc3VGhpcnJSVnZ4ZXdrRTNIdHNJdHdPUk0iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "RsoXgdZDTAshseNObkcZ6DTv7dLd5QAZsh3T1547x5GnRaKdgiN5Mm2nSvZWBj-YV25GHNF-0PpTolAQMjbrQ1p8GMRK-39PKeGkbEa4UJvVC42yMQZxGHsVGuGEo0-8NbmLLR_AfKAVoPutUZyz6dEiCgQDzT6wHdkpaFoQJecwnigTzWYAaoGWxdh2dAW2xWBzwx1RNEwuiXx28Azo00grJHh6F9ttK3jSqbx3bMJhHEjkexbT2nhw5n6aHyGJoqvU3lMotUAVJCgReZlxHuw9yxk9pYtVp9zUL5LMm3m-SRTATWH09iDyPWwbyDzd9sTwFct6odaOMzRE0DkB7A",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInZzY29kZS5kYXRoYWRkZW53ZXRvY2hhZmdlc3Byb2tlbi5ubCIKICAgIH0KICBdCn0"
}
2020-06-19 14:00:38,026:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 366
2020-06-19 14:00:38,027:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Fri, 19 Jun 2020 14:00:37 GMT
Content-Type: application/json
Content-Length: 366
Connection: keep-alive
Boulder-Requester: 89244674
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/89244674/3836056906
Replay-Nonce: 01010PErzQkQ-YRC00e5AJpnTbOnX_PLN-nSFq8h4fvayGE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-06-26T14:00:37.956361907Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "vscode.dathaddenwetochafgesproken.nl"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/5342424347"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/89244674/3836056906"
}
2020-06-19 14:00:38,027:DEBUG:acme.client:Storing nonce: 01010PErzQkQ-YRC00e5AJpnTbOnX_PLN-nSFq8h4fvayGE
2020-06-19 14:00:38,027:DEBUG:acme.client:JWS payload:
b''
2020-06-19 14:00:38,029:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/5342424347:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvODkyNDQ2NzQiLCAibm9uY2UiOiAiMDEwMTBQRXJ6UWtRLVlSQzAwZTVBSnBuVGJPblhfUExOLW5TRnE4aDRmdmF5R0UiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzUzNDI0MjQzNDcifQ",
  "signature": "YozPwiWiHeA3kK-6XLDjlE0Wpk5yTwQQEgkEfi0hM3Veu--J5lVjUCzMGUAcg2ldZV-zIGsqyUlYYXICasEoLczCwEugFPL79-eG3CcEnIcWFZiNCn2uZDhnESCbmre4Osrkl8ymXH045OsjqquZQheE2agmWJ3pxZQ-bG8qkrI9CUo7DOt4JVYZkKb31hKb7HmbX97Cvq7i8nEDn1bP4Y_cXml6OzadKnqbfzZMM9swzQ-LFYOgOKo4HG1K7MGgsroHfN9hjOFiY2oi0NI-kyu9JjQNcTzPzsyNfnSshsK0zDUbOU6PN9BzV9YHg6QrmZIE2JGoO3SM57gjLLiljA",
  "payload": ""
}
2020-06-19 14:00:38,188:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/5342424347 HTTP/1.1" 200 814
2020-06-19 14:00:38,189:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 19 Jun 2020 14:00:38 GMT
Content-Type: application/json
Content-Length: 814
Connection: keep-alive
Boulder-Requester: 89244674
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 01017Q-iRDhUf9gse2EbZQMNAeJql7Zd0Xf92pS79QRwsak
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "vscode.dathaddenwetochafgesproken.nl"
  },
  "status": "pending",
  "expires": "2020-06-26T14:00:37Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5342424347/1Cwpqw",
      "token": "lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5342424347/Cc9vhw",
      "token": "lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5342424347/D2crFQ",
      "token": "lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis"
    }
  ]
}
2020-06-19 14:00:38,189:DEBUG:acme.client:Storing nonce: 01017Q-iRDhUf9gse2EbZQMNAeJql7Zd0Xf92pS79QRwsak
2020-06-19 14:00:38,190:INFO:certbot.auth_handler:Performing the following challenges:
2020-06-19 14:00:38,190:INFO:certbot.auth_handler:http-01 challenge for vscode.dathaddenwetochafgesproken.nl
2020-06-19 14:00:38,190:INFO:certbot.plugins.webroot:Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
2020-06-19 14:00:38,190:DEBUG:certbot.plugins.webroot:Creating root challenges validation dir at /data/letsencrypt-acme-challenge/.well-known/acme-challenge
2020-06-19 14:00:38,193:DEBUG:certbot.plugins.webroot:Attempting to save validation to /data/letsencrypt-acme-challenge/.well-known/acme-challenge/lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis
2020-06-19 14:00:38,194:INFO:certbot.auth_handler:Waiting for verification...
2020-06-19 14:00:38,194:DEBUG:acme.client:JWS payload:
b'{\n  "resource": "challenge",\n  "keyAuthorization": "lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis.GS9pqYUejfYj7GazXqCdrG3FY3AtLWSEsErPRuVAiFg",\n  "type": "http-01"\n}'
2020-06-19 14:00:38,195:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/5342424347/1Cwpqw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvODkyNDQ2NzQiLCAibm9uY2UiOiAiMDEwMTdRLWlSRGhVZjlnc2UyRWJaUU1OQWVKcWw3WmQwWGY5MnBTNzlRUndzYWsiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLXYzLzUzNDI0MjQzNDcvMUN3cHF3In0",
  "signature": "D517i2osxRTtf0OmOBLUcPPS8pEBUiJumqa1oHfOtC-iog4ua9dxS-ZpKAUJ1lr12TJ61epGrF7eNQFxBelOb7jLMan8hOHQ0ow-6q1C-8umis0OJj-w7EeJ3xw76_dAS1_2PuL4DcOlOc8Dxx0pKDF4jY53_8nPmomHEkIeNK1P6aD-LTDndk-tEWq2Vi8Pz_WFgM_lSSFzN-ghENYk6z5AXIf3TMYETHYm_rnRLTs_QE5hU-9uwq0P3cpnebo44DZwMPag1WIzvUwlDxzCJO7wJxEbeN63nouhd3aJDQUjIHe7FiMxkz4T3AK4xrfl64drjJIRO3K6Wh1g9PwO6A",
  "payload": "ewogICJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLAogICJrZXlBdXRob3JpemF0aW9uIjogImxEWUJGQkVzTDRhWTRTSm10cE4xUnNlWUpuRmd4WHJzbHZVQUpMdThtaXMuR1M5cHFZVWVqZllqN0dhelhxQ2RyRzNGWTNBdExXU0VzRXJQUnVWQWlGZyIsCiAgInR5cGUiOiAiaHR0cC0wMSIKfQ"
}
2020-06-19 14:00:38,365:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/5342424347/1Cwpqw HTTP/1.1" 200 185
2020-06-19 14:00:38,366:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 19 Jun 2020 14:00:38 GMT
Content-Type: application/json
Content-Length: 185
Connection: keep-alive
Boulder-Requester: 89244674
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/5342424347>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/5342424347/1Cwpqw
Replay-Nonce: 0102sNVks-uYl7AgKuhv1Q7xAxnBVkPOoD0q6HOizgNJEjs
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5342424347/1Cwpqw",
  "token": "lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis"
}
2020-06-19 14:00:38,366:DEBUG:acme.client:Storing nonce: 0102sNVks-uYl7AgKuhv1Q7xAxnBVkPOoD0q6HOizgNJEjs
2020-06-19 14:00:41,370:DEBUG:acme.client:JWS payload:
b''
2020-06-19 14:00:41,372:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/5342424347:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvODkyNDQ2NzQiLCAibm9uY2UiOiAiMDEwMnNOVmtzLXVZbDdBZ0t1aHYxUTd4QXhuQlZrUE9vRDBxNkhPaXpnTkpFanMiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzUzNDI0MjQzNDcifQ",
  "signature": "ChGfe4D_Hj0xrJDHnjBjn1yewHNdQhfknPcBsqnCj07G-QBr17ubSK-XPKgGrP_L4jFed3QF5JkcXYB3lF7ewwA2fNUcQ2IbRSV9U670tTAdyY9ABYcrkkJj1qlRIyY8z_RqTs28ksfYg1936aQYYnBOkOxQjvWA6fiC-sjhnH58yA4OGkq0fwWFyO36LxpZ4eKUmUYNbam_zPR2Q-plgtk0tb2eUxsTXvCRt_vGARASr379CVlxOm_GolNH6mcEN9sjSrRbhhx3Be0wnOWPYRqT0gwHUvuT7Aevlnf2MUQzDOi0xvZdE2H_y7eONan3JppDd8x2xDe04dAipgdV6Q",
  "payload": ""
}
2020-06-19 14:00:41,530:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/5342424347 HTTP/1.1" 200 1333
2020-06-19 14:00:41,530:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 19 Jun 2020 14:00:41 GMT
Content-Type: application/json
Content-Length: 1333
Connection: keep-alive
Boulder-Requester: 89244674
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102KeaKch77az7eDlYfQUD-Q-jnKZ9XBg8XCbr3xYj84c0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "vscode.dathaddenwetochafgesproken.nl"
  },
  "status": "invalid",
  "expires": "2020-06-26T14:00:37Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "Invalid response from http://vscode.dathaddenwetochafgesproken.nl/.well-known/acme-challenge/lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis [83.83.0.120]: \"\u003chtml\u003e\\r\\n\u003chead\u003e\u003ctitle\u003e404 Not Found\u003c/title\u003e\u003c/head\u003e\\r\\n\u003cbody bgcolor=\\\"white\\\"\u003e\\r\\n\u003ccenter\u003e\u003ch1\u003e404 Not Found\u003c/h1\u003e\u003c/center\u003e\\r\\n\u003chr\u003e\u003ccenter\u003e\"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5342424347/1Cwpqw",
      "token": "lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis",
      "validationRecord": [
        {
          "url": "http://vscode.dathaddenwetochafgesproken.nl/.well-known/acme-challenge/lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis",
          "hostname": "vscode.dathaddenwetochafgesproken.nl",
          "port": "80",
          "addressesResolved": [
            "83.83.0.120"
          ],
          "addressUsed": "83.83.0.120"
        }
      ]
    }
  ]
}
2020-06-19 14:00:41,531:DEBUG:acme.client:Storing nonce: 0102KeaKch77az7eDlYfQUD-Q-jnKZ9XBg8XCbr3xYj84c0
2020-06-19 14:00:41,531:DEBUG:certbot.reporter:Reporting to user: The following errors were reported by the server:

Domain: vscode.dathaddenwetochafgesproken.nl
Type:   unauthorized
Detail: Invalid response from http://vscode.dathaddenwetochafgesproken.nl/.well-known/acme-challenge/lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis [83.83.0.120]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address.
2020-06-19 14:00:41,532:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 82, in handle_authorizations
    self._respond(aauthzrs, resp, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 161, in _respond
    self._poll_challenges(aauthzrs, chall_update, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 232, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
certbot.errors.FailedChallenges: Failed authorization procedure. vscode.dathaddenwetochafgesproken.nl (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://vscode.dathaddenwetochafgesproken.nl/.well-known/acme-challenge/lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis [83.83.0.120]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"

2020-06-19 14:00:41,532:DEBUG:certbot.error_handler:Calling registered functions
2020-06-19 14:00:41,532:INFO:certbot.auth_handler:Cleaning up challenges
2020-06-19 14:00:41,532:DEBUG:certbot.plugins.webroot:Removing /data/letsencrypt-acme-challenge/.well-known/acme-challenge/lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis
2020-06-19 14:00:41,532:DEBUG:certbot.plugins.webroot:All challenges cleaned up
2020-06-19 14:00:41,533:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.30.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1249, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 353, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 389, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 82, in handle_authorizations
    self._respond(aauthzrs, resp, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 161, in _respond
    self._poll_challenges(aauthzrs, chall_update, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 232, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
certbot.errors.FailedChallenges: Failed authorization procedure. vscode.dathaddenwetochafgesproken.nl (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://vscode.dathaddenwetochafgesproken.nl/.well-known/acme-challenge/lDYBFBEsL4aY4SJmtpN1RseYJnFgxXrslvUAJLu8mis [83.83.0.120]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"
